version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: rf-analytics-backend
    ports:
      - "8090:8090"
    restart: unless-stopped
    networks:
      - rf-analytics-network

  frontend:
    build:
      context: ./frontend
    container_name: rf-analytics-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - rf-analytics-network

networks:
  rf-analytics-network:
    driver: bridge
